name: Build
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          version: 1.0-beta.2
      - uses: cjdenio/setup-emojicode@master
        name: Install Emojicode compiler
      - run: sudo apt-get install libgtkmm-3.0-dev
        name: Install gtkmm
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: brew install gtkmm3
        name: Install gtkmm
        if: ${{ matrix.os == 'macos-latest' }}
      - run: ./build.sh
        name: Build
