name: Build
on:
  - push
  - pull_request
jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          version: 1.0-beta.2
      - uses: cjdenio/setup-emojicode@master
        name: Install Emojicode compiler
      - run: sudo apt-get install libgtkmm-3.0-dev
        name: Install gtkmm
      - run: ./build.sh
        name: Build
  build-macos:
    name: MacOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          version: 1.0-beta.2
      - uses: cjdenio/setup-emojicode@master
        name: Install Emojicode compiler
      - run: brew install gtkmm3
        name: Install gtkmm
      - run: ./build.sh
        name: Build
